source 'http://rubygems.org'

# server
gem 'puma'

# sinatra dependencies
gem 'activerecord', '~> 4.1'
gem 'mysql2'
gem 'rake', '~> 10.3'

gem 'sinatra', '~> 1.4'
gem 'sinatra-contrib'
gem 'sinatra-activerecord', '~> 2.0'
gem 'json'
gem 'rack-parser', :require => 'rack/parser'
gem 'newrelic_rpm'

group :development, :test do
  gem 'byebug'
  gem 'guard-rspec', require: false
  gem 'webmock'
end

group :test do
  gem 'ruby-prof'
  gem 'factory_girl', '4.3.0'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-mocks'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'simplecov', :require => false
end